/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import autos.Autos;
import clientes.Clientes;
import contratos.Contratos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import sucursales.Sucursales;
import usuarios.MenuUsuarios;

/**
 *
 * @author Sebastian
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu(int permisos) {
        initComponents();
        if(permisos==1){
            usuarios.setVisible(true);
            contratos.setVisible(false);
            sucursales.setVisible(false);
            clientes.setVisible(false);
            autos.setVisible(false);
        }else
        if(permisos==2){
            usuarios.setVisible(false);
            contratos.setVisible(true);
            sucursales.setVisible(false);
            clientes.setVisible(false);
            autos.setVisible(false);
        }else 
        if(permisos==3){
            usuarios.setVisible(false);
            contratos.setVisible(false);
            sucursales.setVisible(true);
            clientes.setVisible(false);
            autos.setVisible(false);
        }else 
        if(permisos==4){
            usuarios.setVisible(false);
            contratos.setVisible(false);
            sucursales.setVisible(false);
            clientes.setVisible(true);
            autos.setVisible(false);
        }else 
        if(permisos==5){
            usuarios.setVisible(false);
            contratos.setVisible(false);
            sucursales.setVisible(false);
            clientes.setVisible(false);
            autos.setVisible(true);
        }else 
        if(permisos==6){
            usuarios.setVisible(true);
            contratos.setVisible(true);
            sucursales.setVisible(true);
            clientes.setVisible(true);
            autos.setVisible(true);
        }else 
        if(permisos==7){
            usuarios.setVisible(false);
            contratos.setVisible(false);
            sucursales.setVisible(true);
            clientes.setVisible(false);
            autos.setVisible(true);
        }else 
        if(permisos==8){
            usuarios.setVisible(false);
            contratos.setVisible(true);
            sucursales.setVisible(false);
            clientes.setVisible(true);
            autos.setVisible(false);
        }
    }
    
        @Override
            public Image getIconImage() {
                Image retValue = Toolkit.getDefaultToolkit().
                        getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));


                return retValue;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarios = new javax.swing.JButton();
        contratos = new javax.swing.JButton();
        sucursales = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        autos = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("menu test");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuarios.setText("Usuarios");
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });
        getContentPane().add(usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        contratos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contratos.setText("Contratos");
        contratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratosActionPerformed(evt);
            }
        });
        getContentPane().add(contratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        sucursales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sucursales.setText("Sucursales");
        sucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucursalesActionPerformed(evt);
            }
        });
        getContentPane().add(sucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        clientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clientes.setText("Clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        getContentPane().add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        autos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        autos.setText("Autos");
        autos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autosActionPerformed(evt);
            }
        });
        getContentPane().add(autos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Cerrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Quienes somos?");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 190, 80));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        // TODO add your handling code here:
        MenuUsuarios mu=new MenuUsuarios();
        mu.setVisible(true);
    }//GEN-LAST:event_usuariosActionPerformed

    private void contratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratosActionPerformed
        // TODO add your handling code here:
        Contratos c=new Contratos();
        c.setVisible(true);
    }//GEN-LAST:event_contratosActionPerformed

    private void sucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucursalesActionPerformed
        // TODO add your handling code here:
        Sucursales s=new Sucursales();
        s.setVisible(true);
    }//GEN-LAST:event_sucursalesActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
        Clientes c=new Clientes();
        c.setVisible(true);
    }//GEN-LAST:event_clientesActionPerformed

    private void autosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autosActionPerformed
        // TODO add your handling code here:
        Autos a=new Autos();
        a.setVisible(true);
    }//GEN-LAST:event_autosActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        QuienesSomos qs=new QuienesSomos();
        qs.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autos;
    private javax.swing.JButton clientes;
    private javax.swing.JButton contratos;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel logo;
    private javax.swing.JButton sucursales;
    private javax.swing.JButton usuarios;
    // End of variables declaration//GEN-END:variables
}
