/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientes;

import conexion.conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;

/**
 *
 * @author Sebastian
 */
public class Clientes extends javax.swing.JFrame {
    conexion db=new conexion();
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        RadioBoton1();
        RadioBoton2();
        db.mostrarclientes(tabla);
    }
        @Override
            public Image getIconImage() {
                Image retValue = Toolkit.getDefaultToolkit().
                        getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));


                return retValue;
        }
    private void RadioBoton1(){
        ButtonGroup bg=new ButtonGroup();
        bg.add(r1);
        bg.add(r2);
        bg.add(r3);
        r1.setSelected(true);
    }
    private void RadioBoton2(){
        ButtonGroup bg2=new ButtonGroup();
        bg2.add(r4);
        bg2.add(r5);
        bg2.add(r6);
        bg2.add(r7);
        r4.setSelected(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        crear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rut = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        f_nac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();
        editar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rut1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        entrada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        eliminar = new javax.swing.JPanel();
        rut2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        logo2 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        ver = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes enteros de choros");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("rut:");
        crear.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutActionPerformed(evt);
            }
        });
        crear.add(rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 80, 30));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        crear.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nombre:");
        crear.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("fecha nacimiento:");
        crear.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        f_nac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nacActionPerformed(evt);
            }
        });
        crear.add(f_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Sexo:");
        crear.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        r2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r2.setForeground(new java.awt.Color(240, 240, 240));
        r2.setText("Femenino");
        crear.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        r3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r3.setForeground(new java.awt.Color(240, 240, 240));
        r3.setText("otro");
        crear.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        r1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r1.setForeground(new java.awt.Color(240, 240, 240));
        r1.setText("Masculino");
        crear.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        crear.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        crear.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 190, 80));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.png"))); // NOI18N
        crear.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("crear", crear);

        editar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("rut:");
        editar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        rut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rut1ActionPerformed(evt);
            }
        });
        editar.add(rut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, 30));

        jButton2.setText("confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        editar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        r4.setForeground(new java.awt.Color(240, 240, 240));
        r4.setText("rut");
        editar.add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        r5.setForeground(new java.awt.Color(240, 240, 240));
        r5.setText("nombre");
        editar.add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        r6.setForeground(new java.awt.Color(240, 240, 240));
        r6.setText("fecha nacimiento");
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });
        editar.add(r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        r7.setForeground(new java.awt.Color(240, 240, 240));
        r7.setText("sexo");
        editar.add(r7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));
        editar.add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("nuevo valor:");
        editar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, 20));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        editar.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 190, 80));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.png"))); // NOI18N
        editar.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        jTabbedPane1.addTab("editar", editar);

        eliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rut2ActionPerformed(evt);
            }
        });
        eliminar.add(rut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("rut:");
        eliminar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jButton3.setText("eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        eliminar.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        eliminar.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 190, 80));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.png"))); // NOI18N
        eliminar.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        jTabbedPane1.addTab("eliminar", eliminar);

        ver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "rut", "nombre", "fecha nacimiento", "sexo"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        ver.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 440));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.png"))); // NOI18N
        ver.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        jTabbedPane1.addTab("ver", ver);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void f_nacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nacActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sexo="";
        if(r1.isSelected()==true){
            sexo="Maculino";
        }
        if(r2.isSelected()==true){
            sexo="Femenino";
        }
        if(r3.isSelected()==true){
            sexo="Otro";
        }
        db.insertarcliente(rut.getText(), nombre.getText(),f_nac.getText(),sexo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rut1ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (r4.isSelected()==true){
            db.editarcliente(entrada.getText(), rut1.getText(), 1);
        }
        if (r5.isSelected()==true){
            db.editarcliente(entrada.getText(), rut1.getText(), 2);
        }
        if (r6.isSelected()==true){
            db.editarcliente(entrada.getText(), rut1.getText(), 3);
        }
        if (r7.isSelected()==true){
            db.editarcliente(entrada.getText(), rut1.getText(), 4);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rut2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        db.eliminarcliente(rut2.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel crear;
    private javax.swing.JPanel editar;
    private javax.swing.JPanel eliminar;
    private javax.swing.JTextField entrada;
    private javax.swing.JTextField f_nac;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JTextField nombre;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JTextField rut;
    private javax.swing.JTextField rut1;
    private javax.swing.JTextField rut2;
    private javax.swing.JTable tabla;
    private javax.swing.JPanel ver;
    // End of variables declaration//GEN-END:variables
}
